print('=========== DESAFIO 05 ===========')
algo = input('Digite alguma coisa: ')
print(type(algo))
print('Só tem espaços? ', algo.isspace())
print('É número? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanúmerico? ', algo.isalnum())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
